version: "3"

services:
  kafka:
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  app:
    image: bibekbc4/number-app:release-v1.0
    ports: 
      - "80:8080"
    depends_on:
      - kafka
      - db