version: "3"

services:
  db:
    container_name: postgres
    ports:
      - "5432:5432"

  zookeeper:
    container_name: zookeeper
    ports:
      - "2181:2181"
      
  kafka:
    container_name: kafka
    ports:
      - "9092:9092"